2017-11-14 18:06:14,599 - octoprint.server - INFO - --- Log roll over detected ---------------------------------------------------
2017-11-14 18:06:14,602 - octoprint.server - INFO - OctoPrint 1.3.5 (master branch)
2017-11-14 18:06:14,608 - octoprint.plugin.core - INFO - 25 plugin(s) registered with the system:
|  Action Trigger (0.1) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_actiontrigger
|  Announcement Plugin (bundled) = /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.5-py2.7.egg/octoprint/plugins/announcements
|  Automatic Shutdown (0.1.4) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_automaticshutdown
|  Autoselect Plugin (0.2.0) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_autoselect
|  BLTouch Plugin (0.2.0) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_BLTouch
|  Core Wizard (bundled) = /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.5-py2.7.egg/octoprint/plugins/corewizard
|  CuraEngine (<= 15.04) (bundled) = /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.5-py2.7.egg/octoprint/plugins/cura
|  Custom Control Editor (0.2.1) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_customControl
|  Discovery (bundled) = /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.5-py2.7.egg/octoprint/plugins/discovery
|  DisplayProgress (0.1.2) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_displayprogress
|  EEPROM Marlin Editor Plugin (1.0.4) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_eeprom_marlin
|  FileManager (0.1.2) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_filemanager
|  FineTuneRptr (0.774) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_finetunerptr
|  GcodeEditor (0.1.1) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_GcodeEditor
|  OctoPrint Anywhere (0.5.2) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_anywhere
|  Plugin Manager (bundled) = /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.5-py2.7.egg/octoprint/plugins/pluginmanager
|  Print History Plugin (1.2) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_printhistory
|  Printer Stats (1.0.0) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_stats
|  Slic3r (1.1.0) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_slic3r
|  Software Update (bundled) = /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.5-py2.7.egg/octoprint/plugins/softwareupdate
|  STL Viewer (0.3.1) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_stlviewer
|  Tempsgraph Plugin (0.2.2) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_tempsgraph
|  TouchUI (0.3.10) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_touchui
| !Virtual Printer (bundled) = /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.5-py2.7.egg/octoprint/plugins/virtual_printer
|  Yamlpatcher (0.1.1) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_yamlpatcher
2017-11-14 18:06:14,610 - octoprint.server - INFO - ------------------------------------------------------------------------------
2017-11-14 18:06:13,303 - backoff - ERROR - Backing off __probe_auth_token__(...) for 4.5s (SSLError: [Errno 1] _ssl.c:504: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error)
2017-11-14 18:06:13,932 - octoprint.util.connectivity_checker - INFO - Connectivity changed from offline to online
2017-11-14 18:06:17,707 - octoprint.util.connectivity_checker - INFO - Connectivity changed from online to offline
2017-11-14 18:06:18,244 - octoprint.plugins.softwareupdate - INFO - Saved version cache to disk
2017-11-14 18:06:19,256 - octoprint.plugins.announcements - INFO - Loaded channel _important from http://octoprint.org/feeds/important.xml in 4.6s
2017-11-14 18:06:21,225 - octoprint.plugins.announcements - INFO - Looks like we are offline, can't fetch announcements for channel _releases from network
2017-11-14 18:06:21,238 - octoprint.plugins.announcements - INFO - Looks like we are offline, can't fetch announcements for channel _plugins from network
2017-11-14 18:06:22,573 - backoff - ERROR - Backing off capture_mjpeg(...) for 252.7s (URLError: <urlopen error [Errno 111] Connection refused>)
2017-11-14 18:06:39,942 - py.warnings - WARNING - /home/pi/oprint/local/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

2017-11-14 18:06:50,781 - octoprint.plugins.pluginmanager - ERROR - Could not fetch plugins from repository at http://plugins.octoprint.org/plugins.json: HTTPConnectionPool(host='plugins.octoprint.org', port=80): Read timed out.
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.5-py2.7.egg/octoprint/plugins/pluginmanager/__init__.py", line 722, in _fetch_repository_from_url
    r = requests.get(repository_url, timeout=30)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg/requests/sessions.py", line 605, in send
    r.content
  File "/home/pi/oprint/local/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg/requests/models.py", line 750, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg/requests/models.py", line 680, in generate
    raise ConnectionError(e)
ConnectionError: HTTPConnectionPool(host='plugins.octoprint.org', port=80): Read timed out.
2017-11-14 18:06:52,530 - octoprint.plugins.pluginmanager - INFO - Looks like we are offline, can't fetch notices from network
2017-11-14 18:07:03,515 - octoprint.server.preemptive_cache - INFO - ... done in 334167.56s
2017-11-14 18:07:03,516 - octoprint.server.preemptive_cache - INFO - Preemptively caching / (ui _default) for {'query_string': 'l10n=en', 'path': '/', 'base_url': 'http://localhost:5000/'}
2017-11-14 18:07:04,066 - octoprint.server.preemptive_cache - INFO - ... done in 0.55s
2017-11-14 18:07:04,068 - octoprint.server.preemptive_cache - INFO - Preemptively caching / (ui _default) for {'query_string': 'l10n=en', 'path': '/', 'base_url': 'http://192.168.4.102/'}
2017-11-14 18:07:12,587 - octoprint.server.preemptive_cache - INFO - ... done in 8.52s
2017-11-14 18:07:15,549 - octoprint.server.util.sockjs - INFO - New connection from client: 127.0.0.1
2017-11-14 18:07:15,737 - octoprint.server.util.sockjs - INFO - New connection from client: 127.0.0.1
2017-11-14 18:07:22,809 - octoprint.plugins.announcements - INFO - Looks like we are offline, can't fetch announcements for channel _releases from network
2017-11-14 18:07:22,811 - octoprint.plugins.announcements - INFO - Looks like we are offline, can't fetch announcements for channel _plugins from network
2017-11-14 18:10:35,423 - backoff - ERROR - Backing off capture_mjpeg(...) for 281.5s (URLError: <urlopen error [Errno 111] Connection refused>)
2017-11-14 18:10:48,618 - websocket - ERROR - error from callback <function <lambda> at 0x75ba4230>: [Errno 101] Network is unreachable
2017-11-14 18:11:13,618 - websocket - ERROR - error from callback <function <lambda> at 0x75ba4230>: [Errno 101] Network is unreachable
2017-11-14 18:11:38,619 - websocket - ERROR - error from callback <function <lambda> at 0x75ba4230>: [Errno 101] Network is unreachable
2017-11-14 18:12:03,620 - websocket - ERROR - error from callback <function <lambda> at 0x75ba4230>: [Errno 101] Network is unreachable
2017-11-14 18:12:28,620 - websocket - ERROR - error from callback <function <lambda> at 0x75ba4230>: [Errno 101] Network is unreachable
2017-11-14 18:12:53,624 - websocket - ERROR - error from callback <function <lambda> at 0x75ba4230>: [Errno 101] Network is unreachable
2017-11-14 18:13:18,622 - websocket - ERROR - error from callback <function <lambda> at 0x75ba4230>: [Errno 101] Network is unreachable
2017-11-10 21:17:18,714 - octoprint.server - INFO - ******************************************************************************
2017-11-10 21:17:18,717 - octoprint.server - INFO - Starting OctoPrint 1.3.5 (master branch)
2017-11-10 21:17:18,718 - octoprint.server - WARNING - requests/urllib3 will run in an insecure SSL environment. You might see corresponding warnings logged later ("InsecurePlatformWarning"). It is recommended to either update to a Python version >= 2.7.9 or alternatively install PyOpenSSL plus its dependencies. For details see https://urllib3.readthedocs.org/en/latest/security.html#openssl-pyopenssl
2017-11-10 21:17:18,719 - octoprint.server - INFO - ******************************************************************************
2017-11-10 21:17:19,131 - octoprint.plugin.core - INFO - Loading plugins from /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.5-py2.7.egg/octoprint/plugins, /home/pi/.octoprint/plugins and installed plugin packages...
2017-11-10 21:17:24,809 - octoprint.plugin.core - INFO - Found 25 plugin(s) providing 24 mixin implementations, 21 hook handlers
2017-11-10 21:17:24,897 - octoprint.server - INFO - Intermediary server started
2017-11-10 21:17:24,898 - octoprint.plugin.core - INFO - Loading plugins from /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.5-py2.7.egg/octoprint/plugins, /home/pi/.octoprint/plugins and installed plugin packages...
2017-11-10 21:17:25,014 - octoprint.plugin.core - INFO - Found 25 plugin(s) providing 24 mixin implementations, 21 hook handlers
2017-11-10 21:17:25,075 - octoprint.filemanager.storage - INFO - Initializing the file metadata for /home/pi/.octoprint/uploads...
2017-11-10 21:17:25,708 - octoprint.filemanager.storage - INFO - ... file metadata for /home/pi/.octoprint/uploads initialized successfully.
2017-11-10 21:17:26,192 - octoprint.plugins.softwareupdate - INFO - Loaded version cache from disk
2017-11-10 21:17:30,047 - octoprint.util.pip - INFO - Using "/home/pi/oprint/bin/python -c import sys; sys.argv = ['pip'] + sys.argv[1:]; import pip; pip.main()" as command to invoke pip
2017-11-10 21:17:31,824 - octoprint.util.pip - INFO - Version of pip is 1.1
2017-11-10 21:17:31,827 - octoprint.plugin.core - INFO - Initialized 24 plugin implementation(s)
2017-11-10 21:17:31,846 - octoprint.plugin.core - INFO - 25 plugin(s) registered with the system:
|  Action Trigger (0.1) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_actiontrigger
|  Announcement Plugin (bundled) = /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.5-py2.7.egg/octoprint/plugins/announcements
|  Automatic Shutdown (0.1.4) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_automaticshutdown
|  Autoselect Plugin (0.2.0) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_autoselect
|  BLTouch Plugin (0.2.0) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_BLTouch
|  Core Wizard (bundled) = /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.5-py2.7.egg/octoprint/plugins/corewizard
|  CuraEngine (<= 15.04) (bundled) = /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.5-py2.7.egg/octoprint/plugins/cura
|  Custom Control Editor (0.2.1) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_customControl
|  Discovery (bundled) = /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.5-py2.7.egg/octoprint/plugins/discovery
|  DisplayProgress (0.1.2) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_displayprogress
|  EEPROM Marlin Editor Plugin (1.0.4) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_eeprom_marlin
|  FileManager (0.1.2) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_filemanager
|  FineTuneRptr (0.774) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_finetunerptr
|  GcodeEditor (0.1.1) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_GcodeEditor
|  OctoPrint Anywhere (0.5.2) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_anywhere
|  Plugin Manager (bundled) = /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.5-py2.7.egg/octoprint/plugins/pluginmanager
|  Print History Plugin (1.2) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_printhistory
|  Printer Stats (1.0.0) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_stats
|  Slic3r (1.1.0) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_slic3r
|  Software Update (bundled) = /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.5-py2.7.egg/octoprint/plugins/softwareupdate
|  STL Viewer (0.3.1) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_stlviewer
|  Tempsgraph Plugin (0.2.2) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_tempsgraph
|  TouchUI (0.3.10) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_touchui
| !Virtual Printer (bundled) = /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.5-py2.7.egg/octoprint/plugins/virtual_printer
|  Yamlpatcher (0.1.1) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_yamlpatcher
2017-11-10 21:17:31,860 - octoprint.server - INFO - Reset webasset folder /home/pi/.octoprint/generated/webassets...
2017-11-10 21:17:31,891 - octoprint.server - INFO - Reset webasset folder /home/pi/.octoprint/generated/.webassets-cache...
2017-11-10 21:17:34,723 - octoprint.server.util.flask.collect_plugin_assets - WARNING - Plugin GcodeEditor is referring to non existing css asset css/GcodeEditor.css
2017-11-10 21:17:36,665 - octoprint.server - INFO - Shutting down intermediary server...
2017-11-10 21:17:37,029 - octoprint.server - INFO - Intermediary server shut down
2017-11-10 21:17:37,049 - octoprint.events - INFO - Processing startup event, this is our first event
2017-11-10 21:17:37,050 - octoprint.events - INFO - Adding 0 events to queue that were held back before startup event
2017-11-10 21:17:37,120 - octoprint.filemanager - INFO - Adding backlog items from all storage types to analysis queue...
2017-11-10 21:17:37,196 - octoprint.filemanager - INFO - Added 0 items from storage type "local" to analysis queue
2017-11-10 21:17:37,308 - octoprint.util.comm - INFO - M110 detected, setting current line number to 0
2017-11-10 21:17:37,326 - octoprint.plugins.discovery - INFO - Registered OctoPrint instance "Prusa" for _http._tcp
2017-11-10 21:17:37,342 - octoprint.plugins.discovery - INFO - Registered OctoPrint instance "Prusa" for _octoprint._tcp
2017-11-10 21:17:37,347 - octoprint.plugins.discovery - INFO - Registered OctoPrint instance "Prusa" for SSDP
2017-11-10 21:17:37,363 - octoprint.server - INFO - Listening on http://127.0.0.1:5000
2017-11-10 21:17:37,496 - backoff - ERROR - Backing off capture_mjpeg(...) for 0.1s (URLError: <urlopen error [Errno 111] Connection refused>)
2017-11-10 21:17:37,627 - backoff - ERROR - Backing off capture_mjpeg(...) for 1.5s (URLError: <urlopen error [Errno 111] Connection refused>)
2017-11-10 21:17:37,642 - octoprint.server.util.sockjs - INFO - New connection from client: 127.0.0.1
2017-11-10 21:17:37,822 - octoprint.plugins.stats - INFO - Printer Stats
2017-11-10 21:17:37,974 - octoprint.plugins.pluginmanager - INFO - Loaded plugin repository data from disk, was still valid
2017-11-10 21:17:38,093 - octoprint.plugins.pluginmanager - INFO - Loaded notice data from disk, was still valid
2017-11-10 21:17:38,200 - octoprint.plugins.stlviewer - INFO - STL Viewer loaded!
2017-11-10 21:17:38,284 - octoprint.server.preemptive_cache - INFO - Preemptively caching / (ui _default) for {'query_string': 'l10n=en', 'path': '/', 'base_url': 'http://192.168.1.83/'}
2017-11-10 21:17:38,363 - octoprint.util.comm - INFO - M110 detected, setting current line number to 0
2017-11-10 21:17:39,126 - backoff - ERROR - Backing off capture_mjpeg(...) for 2.1s (URLError: <urlopen error [Errno 111] Connection refused>)
2017-11-10 21:17:39,883 - octoprint.util.comm - INFO - M110 detected, setting current line number to 0
2017-11-10 21:17:39,966 - octoprint.util.comm - INFO - Printer reports firmware name "Marlin 1.1.6 (Github)"
2017-11-10 21:17:39,975 - octoprint.util.comm - INFO - Firmware states that it supports temperature autoreporting
2017-11-10 21:17:41,205 - backoff - ERROR - Backing off capture_mjpeg(...) for 4.0s (URLError: <urlopen error [Errno 111] Connection refused>)
2017-11-10 21:17:45,270 - backoff - ERROR - Backing off capture_mjpeg(...) for 12.9s (URLError: <urlopen error [Errno 111] Connection refused>)
2017-11-10 21:17:47,012 - octoprint.util.pip - INFO - Using "/home/pi/oprint/bin/python -c import sys; sys.argv = ['pip'] + sys.argv[1:]; import pip; pip.main()" as command to invoke pip
2017-11-10 21:17:47,580 - backoff - ERROR - Backing off __probe_auth_token__(...) for 1.0s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:17:47,779 - octoprint.util.pip - INFO - Using "/home/pi/oprint/bin/python -c import sys; sys.argv = ['pip'] + sys.argv[1:]; import pip; pip.main()" as command to invoke pip
2017-11-10 21:17:47,984 - octoprint.util.pip - INFO - Using "/home/pi/oprint/bin/python -c import sys; sys.argv = ['pip'] + sys.argv[1:]; import pip; pip.main()" as command to invoke pip
2017-11-10 21:17:48,344 - octoprint.util.pip - INFO - Using "/home/pi/oprint/bin/python -c import sys; sys.argv = ['pip'] + sys.argv[1:]; import pip; pip.main()" as command to invoke pip
2017-11-10 21:17:48,591 - backoff - ERROR - Backing off __probe_auth_token__(...) for 4.7s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:17:48,683 - octoprint.util.pip - INFO - Using "/home/pi/oprint/bin/python -c import sys; sys.argv = ['pip'] + sys.argv[1:]; import pip; pip.main()" as command to invoke pip
2017-11-10 21:17:53,298 - backoff - ERROR - Backing off __probe_auth_token__(...) for 2.1s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:17:57,926 - backoff - ERROR - Backing off __probe_auth_token__(...) for 2.4s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:17:58,150 - backoff - ERROR - Backing off capture_mjpeg(...) for 18.5s (URLError: <urlopen error [Errno 111] Connection refused>)
2017-11-10 21:18:00,277 - octoprint.util.pip - INFO - pip installs to /home/pi/oprint/lib/python2.7/site-packages/, --user flag needed => no, virtual env => yes
2017-11-10 21:18:01,012 - backoff - ERROR - Backing off __probe_auth_token__(...) for 0.0s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:18:01,113 - octoprint.plugins.softwareupdate - INFO - Saved version cache to disk
2017-11-10 21:18:01,265 - backoff - ERROR - Backing off __probe_auth_token__(...) for 2.5s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:18:03,995 - backoff - ERROR - Backing off __probe_auth_token__(...) for 4.0s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:18:08,112 - backoff - ERROR - Backing off __probe_auth_token__(...) for 2.9s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:18:11,060 - backoff - ERROR - Backing off __probe_auth_token__(...) for 4.9s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:18:16,480 - backoff - ERROR - Backing off __probe_auth_token__(...) for 0.0s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:18:16,674 - backoff - ERROR - Backing off __probe_auth_token__(...) for 3.1s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:18:17,181 - backoff - ERROR - Backing off capture_mjpeg(...) for 60.3s (URLError: <urlopen error [Errno 111] Connection refused>)
2017-11-10 21:18:19,882 - backoff - ERROR - Backing off __probe_auth_token__(...) for 5.0s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:18:24,861 - backoff - ERROR - Backing off __probe_auth_token__(...) for 2.6s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:18:27,523 - backoff - ERROR - Backing off __probe_auth_token__(...) for 2.0s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:18:29,578 - backoff - ERROR - Backing off __probe_auth_token__(...) for 3.6s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:18:33,485 - backoff - ERROR - Backing off __probe_auth_token__(...) for 4.2s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:18:37,666 - backoff - ERROR - Backing off __probe_auth_token__(...) for 3.4s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:18:41,120 - backoff - ERROR - Backing off __probe_auth_token__(...) for 3.1s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:18:41,672 - octoprint.server.preemptive_cache - INFO - ... done in 63.39s
2017-11-10 21:18:41,673 - octoprint.server.preemptive_cache - INFO - Preemptively caching / (ui _default) for {'query_string': 'l10n=en', 'path': '/', 'base_url': 'http://localhost:5000/'}
2017-11-10 21:18:41,824 - websocket - ERROR - error from callback <function <lambda> at 0x33c5b30>: [Errno 101] Network is unreachable
2017-11-10 21:18:41,880 - octoprint.server.preemptive_cache - INFO - ... done in 0.21s
2017-11-10 21:18:41,881 - octoprint.server.preemptive_cache - INFO - Preemptively caching / (ui _default) for {'query_string': 'l10n=en', 'path': '/', 'base_url': 'http://192.168.4.102/'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   2017-11-10 21:17:19,503 - octoprint.server - INFO - ******************************************************************************
2017-11-10 21:17:19,506 - octoprint.server - INFO - Starting OctoPrint 1.3.5 (master branch)
2017-11-10 21:17:19,507 - octoprint.server - WARNING - requests/urllib3 will run in an insecure SSL environment. You might see corresponding warnings logged later ("InsecurePlatformWarning"). It is recommended to either update to a Python version >= 2.7.9 or alternatively install PyOpenSSL plus its dependencies. For details see https://urllib3.readthedocs.org/en/latest/security.html#openssl-pyopenssl
2017-11-10 21:17:19,508 - octoprint.server - INFO - ******************************************************************************
2017-11-10 21:17:19,892 - octoprint.plugin.core - INFO - Loading plugins from /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.5-py2.7.egg/octoprint/plugins, /home/pi/.octoprint/plugins and installed plugin packages...
2017-11-10 21:17:24,010 - octoprint.plugin.core - INFO - Found 25 plugin(s) providing 24 mixin implementations, 21 hook handlers
2017-11-10 21:17:24,097 - octoprint.server - INFO - Intermediary server started
2017-11-10 21:17:24,099 - octoprint.plugin.core - INFO - Loading plugins from /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.5-py2.7.egg/octoprint/plugins, /home/pi/.octoprint/plugins and installed plugin packages...
2017-11-10 21:17:24,198 - octoprint.plugin.core - INFO - Found 25 plugin(s) providing 24 mixin implementations, 21 hook handlers
2017-11-10 21:17:24,259 - octoprint.filemanager.storage - INFO - Initializing the file metadata for /home/pi/.octoprint/uploads...
2017-11-10 21:17:24,921 - octoprint.filemanager.storage - INFO - ... file metadata for /home/pi/.octoprint/uploads initialized successfully.
2017-11-10 21:17:25,436 - octoprint.plugins.softwareupdate - INFO - Loaded version cache from disk
2017-11-10 21:17:28,934 - octoprint.util.pip - INFO - Using "/home/pi/oprint/bin/python -c import sys; sys.argv = ['pip'] + sys.argv[1:]; import pip; pip.main()" as command to invoke pip
2017-11-10 21:17:30,712 - octoprint.util.pip - INFO - Version of pip is 1.1
2017-11-10 21:17:30,715 - octoprint.plugin.core - INFO - Initialized 24 plugin implementation(s)
2017-11-10 21:17:30,735 - octoprint.plugin.core - INFO - 25 plugin(s) registered with the system:
|  Action Trigger (0.1) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_actiontrigger
|  Announcement Plugin (bundled) = /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.5-py2.7.egg/octoprint/plugins/announcements
|  Automatic Shutdown (0.1.4) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_automaticshutdown
|  Autoselect Plugin (0.2.0) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_autoselect
|  BLTouch Plugin (0.2.0) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_BLTouch
|  Core Wizard (bundled) = /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.5-py2.7.egg/octoprint/plugins/corewizard
|  CuraEngine (<= 15.04) (bundled) = /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.5-py2.7.egg/octoprint/plugins/cura
|  Custom Control Editor (0.2.1) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_customControl
|  Discovery (bundled) = /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.5-py2.7.egg/octoprint/plugins/discovery
|  DisplayProgress (0.1.2) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_displayprogress
|  EEPROM Marlin Editor Plugin (1.0.4) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_eeprom_marlin
|  FileManager (0.1.2) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_filemanager
|  FineTuneRptr (0.774) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_finetunerptr
|  GcodeEditor (0.1.1) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_GcodeEditor
|  OctoPrint Anywhere (0.5.2) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_anywhere
|  Plugin Manager (bundled) = /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.5-py2.7.egg/octoprint/plugins/pluginmanager
|  Print History Plugin (1.2) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_printhistory
|  Printer Stats (1.0.0) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_stats
|  Slic3r (1.1.0) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_slic3r
|  Software Update (bundled) = /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.5-py2.7.egg/octoprint/plugins/softwareupdate
|  STL Viewer (0.3.1) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_stlviewer
|  Tempsgraph Plugin (0.2.2) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_tempsgraph
|  TouchUI (0.3.10) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_touchui
| !Virtual Printer (bundled) = /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.5-py2.7.egg/octoprint/plugins/virtual_printer
|  Yamlpatcher (0.1.1) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_yamlpatcher
2017-11-10 21:17:30,748 - octoprint.server - INFO - Reset webasset folder /home/pi/.octoprint/generated/webassets...
2017-11-10 21:17:30,779 - octoprint.server - INFO - Reset webasset folder /home/pi/.octoprint/generated/.webassets-cache...
2017-11-10 21:17:30,794 - octoprint.server.util.flask.collect_plugin_assets - WARNING - Plugin GcodeEditor is referring to non existing css asset css/GcodeEditor.css
2017-11-10 21:17:36,094 - octoprint.server - INFO - Shutting down intermediary server...
2017-11-10 21:17:36,298 - octoprint.server - INFO - Intermediary server shut down
2017-11-10 21:17:36,317 - octoprint.events - INFO - Processing startup event, this is our first event
2017-11-10 21:17:36,340 - octoprint.events - INFO - Adding 0 events to queue that were held back before startup event
2017-11-10 21:17:36,387 - octoprint.filemanager - INFO - Adding backlog items from all storage types to analysis queue...
2017-11-10 21:17:36,460 - octoprint.filemanager - INFO - Added 0 items from storage type "local" to analysis queue
2017-11-10 21:17:36,579 - octoprint.util.comm - INFO - M110 detected, setting current line number to 0
2017-11-10 21:17:36,589 - octoprint.plugins.discovery - INFO - Registered OctoPrint instance "Prusa" for _http._tcp
2017-11-10 21:17:36,606 - octoprint.plugins.discovery - INFO - Registered OctoPrint instance "Prusa" for _octoprint._tcp
2017-11-10 21:17:36,614 - octoprint.server - INFO - Listening on http://127.0.0.1:5000
2017-11-10 21:17:36,869 - backoff - ERROR - Backing off __probe_auth_token__(...) for 1.8s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:17:36,911 - octoprint.server.util.sockjs - INFO - New connection from client: 127.0.0.1
2017-11-10 21:17:36,912 - backoff - ERROR - Backing off capture_mjpeg(...) for 0.6s (URLError: <urlopen error [Errno 111] Connection refused>)
2017-11-10 21:17:37,244 - octoprint.plugins.pluginmanager - INFO - Loaded plugin repository data from disk, was still valid
2017-11-10 21:17:37,264 - octoprint.plugins.stats - INFO - Printer Stats
2017-11-10 21:17:37,347 - octoprint.plugins.pluginmanager - INFO - Loaded notice data from disk, was still valid
2017-11-10 21:17:37,509 - octoprint.util.comm - INFO - M110 detected, setting current line number to 0
2017-11-10 21:17:37,577 - backoff - ERROR - Backing off capture_mjpeg(...) for 0.6s (URLError: <urlopen error [Errno 111] Connection refused>)
2017-11-10 21:17:37,782 - octoprint.plugins.stlviewer - INFO - STL Viewer loaded!
2017-11-10 21:17:37,968 - octoprint.server.preemptive_cache - INFO - Preemptively caching / (ui _default) for {'query_string': 'l10n=en', 'path': '/', 'base_url': 'http://192.168.1.83/'}
2017-11-10 21:17:39,453 - backoff - ERROR - Backing off capture_mjpeg(...) for 1.1s (URLError: <urlopen error [Errno 111] Connection refused>)
2017-11-10 21:17:39,479 - octoprint.util.comm - INFO - M110 detected, setting current line number to 0
2017-11-10 21:17:39,498 - backoff - ERROR - Backing off __probe_auth_token__(...) for 3.1s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:17:39,558 - octoprint.util.comm - INFO - Printer reports firmware name "Marlin 1.1.6 (Github)"
2017-11-10 21:17:39,574 - octoprint.util.comm - INFO - Firmware states that it supports temperature autoreporting
2017-11-10 21:17:40,569 - backoff - ERROR - Backing off capture_mjpeg(...) for 2.5s (URLError: <urlopen error [Errno 111] Connection refused>)
2017-11-10 21:17:42,649 - backoff - ERROR - Backing off __probe_auth_token__(...) for 4.2s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:17:43,093 - backoff - ERROR - Backing off capture_mjpeg(...) for 4.1s (URLError: <urlopen error [Errno 111] Connection refused>)
2017-11-10 21:17:43,648 - octoprint.util.pip - INFO - Using "/home/pi/oprint/bin/python -c import sys; sys.argv = ['pip'] + sys.argv[1:]; import pip; pip.main()" as command to invoke pip
2017-11-10 21:17:43,660 - octoprint.util.pip - INFO - Using "/home/pi/oprint/bin/python -c import sys; sys.argv = ['pip'] + sys.argv[1:]; import pip; pip.main()" as command to invoke pip
2017-11-10 21:17:43,795 - octoprint.util.pip - INFO - Using "/home/pi/oprint/bin/python -c import sys; sys.argv = ['pip'] + sys.argv[1:]; import pip; pip.main()" as command to invoke pip
2017-11-10 21:17:43,926 - octoprint.util.pip - INFO - Using "/home/pi/oprint/bin/python -c import sys; sys.argv = ['pip'] + sys.argv[1:]; import pip; pip.main()" as command to invoke pip
2017-11-10 21:17:43,947 - octoprint.util.pip - INFO - Using "/home/pi/oprint/bin/python -c import sys; sys.argv = ['pip'] + sys.argv[1:]; import pip; pip.main()" as command to invoke pip
2017-11-10 21:17:46,914 - backoff - ERROR - Backing off __probe_auth_token__(...) for 1.9s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:17:47,228 - backoff - ERROR - Backing off capture_mjpeg(...) for 1.2s (URLError: <urlopen error [Errno 111] Connection refused>)
2017-11-10 21:17:48,472 - backoff - ERROR - Backing off capture_mjpeg(...) for 33.8s (URLError: <urlopen error [Errno 111] Connection refused>)
2017-11-10 21:17:48,794 - backoff - ERROR - Backing off __probe_auth_token__(...) for 2.2s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:17:51,002 - backoff - ERROR - Backing off __probe_auth_token__(...) for 3.6s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:17:58,147 - backoff - ERROR - Backing off __probe_auth_token__(...) for 0.5s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:17:58,675 - backoff - ERROR - Backing off __probe_auth_token__(...) for 0.0s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:17:58,717 - backoff - ERROR - Backing off __probe_auth_token__(...) for 3.1s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:18:01,870 - backoff - ERROR - Backing off __probe_auth_token__(...) for 0.1s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:18:03,245 - backoff - ERROR - Backing off __probe_auth_token__(...) for 2.6s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:18:06,043 - backoff - ERROR - Backing off __probe_auth_token__(...) for 1.8s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:18:07,826 - backoff - ERROR - Backing off __probe_auth_token__(...) for 2.0s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:18:08,800 - octoprint.util.pip - INFO - pip installs to /home/pi/oprint/lib/python2.7/site-packages/, --user flag needed => no, virtual env => yes
2017-11-10 21:18:09,287 - octoprint.plugins.softwareupdate - INFO - Saved version cache to disk
2017-11-10 21:18:10,366 - backoff - ERROR - Backing off __probe_auth_token__(...) for 4.2s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:18:14,654 - backoff - ERROR - Backing off __probe_auth_token__(...) for 3.9s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:18:18,680 - backoff - ERROR - Backing off __probe_auth_token__(...) for 2.8s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:18:22,008 - backoff - ERROR - Backing off __probe_auth_token__(...) for 1.5s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:18:22,334 - backoff - ERROR - Backing off capture_mjpeg(...) for 46.3s (URLError: <urlopen error [Errno 111] Connection refused>)
2017-11-10 21:18:26,072 - backoff - ERROR - Backing off __probe_auth_token__(...) for 4.8s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:18:30,977 - backoff - ERROR - Backing off __probe_auth_token__(...) for 4.1s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:18:35,068 - backoff - ERROR - Backing off __probe_auth_token__(...) for 0.5s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:18:35,554 - backoff - ERROR - Backing off __probe_auth_token__(...) for 2.0s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:18:37,607 - backoff - ERROR - Backing off __probe_auth_token__(...) for 3.9s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:18:41,503 - backoff - ERROR - Backing off __probe_auth_token__(...) for 2.9s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:18:44,603 - backoff - ERROR - Backing off __probe_auth_token__(...) for 2.4s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:18:47,184 - backoff - ERROR - Backing off __probe_auth_token__(...) for 2.6s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:18:49,996 - backoff - ERROR - Backing off __probe_auth_token__(...) for 2.4s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:18:52,356 - octoprint.server.preemptive_cache - INFO - ... done in 74.39s
2017-11-10 21:18:52,358 - octoprint.server.preemptive_cache - INFO - Preemptively caching / (ui _default) for {'query_string': 'l10n=en', 'path': '/', 'base_url': 'http://localhost:5000/'}
2017-11-10 21:18:52,401 - backoff - ERROR - Backing off __probe_auth_token__(...) for 3.9s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:18:52,493 - websocket - ERROR - error from callback <function <lambda> at 0x23ee330>: [Errno 101] Network is unreachable
2017-11-10 21:18:52,766 - octoprint.server.preemptive_cache - INFO - ... done in 0.41s
2017-11-10 21:18:52,768 - octoprint.server.preemptive_cache - INFO - Preemptively caching / (ui _default) for {'query_string': 'l10n=en', 'path': '/', 'base_url': 'http://192.168.4.102/'}
2017-11-10 21:18:57,448 - backoff - ERROR - Backing off __probe_auth_token__(...) for 4.7s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:19:01,382 - octoprint.server.preemptive_cache - INFO - ... done in 8.61s
2017-11-10 21:19:02,193 - backoff - ERROR - Backing off __probe_auth_token__(...) for 1.8s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:19:03,373 - octoprint.server.util.sockjs - INFO - New connection from client: 127.0.0.1
2017-11-10 21:19:03,664 - octoprint.server.util.sockjs - INFO - New connection from client: 127.0.0.1
2017-11-10 21:19:04,008 - backoff - ERROR - Backing off __probe_auth_token__(...) for 3.0s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:19:07,001 - backoff - ERROR - Backing off __probe_auth_token__(...) for 5.0s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:19:08,679 - backoff - ERROR - Backing off capture_mjpeg(...) for 163.2s (URLError: <urlopen error [Errno 111] Connection refused>)
2017-11-10 21:19:12,335 - backoff - ERROR - Backing off __probe_auth_token__(...) for 4.4s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:19:16,799 - backoff - ERROR - Backing off __probe_auth_token__(...) for 0.2s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:19:17,051 - backoff - ERROR - Backing off __probe_auth_token__(...) for 1.4s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:19:17,461 - websocket - ERROR - error from callback <function <lambda> at 0x23ee330>: [Errno 101] Network is unreachable
2017-11-10 21:19:18,458 - backoff - ERROR - Backing off __probe_auth_token__(...) for 0.3s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:19:18,758 - backoff - ERROR - Backing off __probe_auth_token__(...) for 0.8s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:19:19,579 - backoff - ERROR - Backing off __probe_auth_token__(...) for 0.7s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:19:20,275 - backoff - ERROR - Backing off __probe_auth_token__(...) for 3.0s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:19:23,253 - backoff - ERROR - Backing off __probe_auth_token__(...) for 1.6s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:19:24,911 - backoff - ERROR - Backing off __probe_auth_token__(...) for 2.9s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:19:27,865 - backoff - ERROR - Backing off __probe_auth_token__(...) for 4.6s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:19:32,451 - backoff - ERROR - Backing off __probe_auth_token__(...) for 0.8s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:19:33,285 - backoff - ERROR - Backing off __probe_auth_token__(...) for 2.2s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:19:35,533 - backoff - ERROR - Backing off __probe_auth_token__(...) for 1.2s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:19:36,763 - backoff - ERROR - Backing off __probe_auth_token__(...) for 2.4s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:19:39,224 - backoff - ERROR - Backing off __probe_auth_token__(...) for 4.1s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:19:42,463 - websocket - ERROR - error from callback <function <lambda> at 0x23ee330>: [Errno 101] Network is unreachable
2017-11-10 21:19:43,317 - backoff - ERROR - Backing off __probe_auth_token__(...) for 4.7s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:19:48,063 - backoff - ERROR - Backing off __probe_auth_token__(...) for 4.7s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:19:52,810 - backoff - ERROR - Backing off __probe_auth_token__(...) for 1.7s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:19:54,534 - backoff - ERROR - Backing off __probe_auth_token__(...) for 0.4s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:19:54,968 - backoff - ERROR - Backing off __probe_auth_token__(...) for 1.2s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:19:56,139 - backoff - ERROR - Backing off __probe_auth_token__(...) for 0.6s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:19:56,719 - backoff - ERROR - Backing off __probe_auth_token__(...) for 3.8s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:20:00,489 - backoff - ERROR - Backing off __probe_auth_token__(...) for 2.6s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:20:03,067 - backoff - ERROR - Backing off __probe_auth_token__(...) for 3.4s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:20:06,486 - backoff - ERROR - Backing off __probe_auth_token__(...) for 0.3s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:20:06,789 - backoff - ERROR - Backing off __probe_auth_token__(...) for 2.9s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:20:07,466 - websocket - ERROR - error from callback <function <lambda> at 0x23ee330>: [Errno 101] Network is unreachable
2017-11-10 21:20:09,726 - backoff - ERROR - Backing off __probe_auth_token__(...) for 0.4s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:20:10,172 - backoff - ERROR - Backing off __probe_auth_token__(...) for 4.6s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:20:14,772 - backoff - ERROR - Backing off __probe_auth_token__(...) for 1.7s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:20:16,500 - backoff - ERROR - Backing off __probe_auth_token__(...) for 2.5s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:20:19,103 - backoff - ERROR - Backing off __probe_auth_token__(...) for 4.4s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:20:23,512 - backoff - ERROR - Backing off __probe_auth_token__(...) for 1.6s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:20:25,081 - backoff - ERROR - Backing off __probe_auth_token__(...) for 4.5s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:20:29,567 - backoff - ERROR - Backing off __probe_auth_token__(...) for 2.8s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:20:32,424 - backoff - ERROR - Backing off __probe_auth_token__(...) for 0.4s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:20:32,464 - websocket - ERROR - error from callback <function <lambda> at 0x23ee330>: [Errno 101] Network is unreachable
2017-11-10 21:20:32,872 - backoff - ERROR - Backing off __probe_auth_token__(...) for 1.2s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:20:34,077 - backoff - ERROR - Backing off __probe_auth_token__(...) for 1.3s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:20:35,392 - backoff - ERROR - Backing off __probe_auth_token__(...) for 0.7s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:20:36,127 - backoff - ERROR - Backing off __probe_auth_token__(...) for 1.6s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:20:37,694 - backoff - ERROR - Backing off __probe_auth_token__(...) for 3.9s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:20:41,604 - backoff - ERROR - Backing off __probe_auth_token__(...) for 0.3s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:20:41,879 - backoff - ERROR - Backing off __probe_auth_token__(...) for 1.1s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:20:42,991 - backoff - ERROR - Backing off __probe_auth_token__(...) for 1.7s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:20:44,664 - backoff - ERROR - Backing off __probe_auth_token__(...) for 0.2s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:20:44,837 - backoff - ERROR - Backing off __probe_auth_token__(...) for 4.1s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:20:48,913 - backoff - ERROR - Backing off __probe_auth_token__(...) for 3.8s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:20:52,724 - backoff - ERROR - Backing off __probe_auth_token__(...) for 2.0s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:20:54,710 - backoff - ERROR - Backing off __probe_auth_token__(...) for 2.5s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:20:57,214 - backoff - ERROR - Backing off __probe_auth_token__(...) for 2.7s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:20:57,465 - websocket - ERROR - error from callback <function <lambda> at 0x23ee330>: [Errno 101] Network is unreachable
2017-11-10 21:20:59,891 - backoff - ERROR - Backing off __probe_auth_token__(...) for 3.1s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:21:03,013 - backoff - ERROR - Backing off __probe_auth_token__(...) for 3.9s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:21:06,883 - backoff - ERROR - Backing off __probe_auth_token__(...) for 0.9s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:21:07,826 - backoff - ERROR - Backing off __probe_auth_token__(...) for 5.0s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:21:12,799 - backoff - ERROR - Backing off __probe_auth_token__(...) for 2.1s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:21:14,947 - backoff - ERROR - Backing off __probe_auth_token__(...) for 2.5s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:21:17,489 - backoff - ERROR - Backing off __probe_auth_token__(...) for 3.9s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
2017-11-10 21:21:21,394 - backoff - ERROR - Backing off __probe_auth_token__(...) for 3.5s (ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known')))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         2017-11-10 21:17:15,578 - octoprint.server - INFO - ******************************************************************************
2017-11-10 21:17:15,580 - octoprint.server - INFO - Starting OctoPrint 1.3.5 (master branch)
2017-11-10 21:17:15,581 - octoprint.server - WARNING - requests/urllib3 will run in an insecure SSL environment. You might see corresponding warnings logged later ("InsecurePlatformWarning"). It is recommended to either update to a Python version >= 2.7.9 or alternatively install PyOpenSSL plus its dependencies. For details see https://urllib3.readthedocs.org/en/latest/security.html#openssl-pyopenssl
2017-11-10 21:17:15,582 - octoprint.server - INFO - ******************************************************************************
2017-11-10 21:17:15,866 - octoprint.plugin.core - INFO - Loading plugins from /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.5-py2.7.egg/octoprint/plugins, /home/pi/.octoprint/plugins and installed plugin packages...
2017-11-10 21:17:19,214 - octoprint.plugin.core - INFO - Found 25 plugin(s) providing 24 mixin implementations, 21 hook handlers
2017-11-10 21:17:19,302 - octoprint.server - INFO - Intermediary server started
2017-11-10 21:17:19,303 - octoprint.plugin.core - INFO - Loading plugins from /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.5-py2.7.egg/octoprint/plugins, /home/pi/.octoprint/plugins and installed plugin packages...
2017-11-10 21:17:19,406 - octoprint.plugin.core - INFO - Found 25 plugin(s) providing 24 mixin implementations, 21 hook handlers
2017-11-10 21:17:19,467 - octoprint.filemanager.storage - INFO - Initializing the file metadata for /home/pi/.octoprint/uploads...
2017-11-10 21:17:21,348 - octoprint.filemanager.storage - INFO - ... file metadata for /home/pi/.octoprint/uploads initialized successfully.
2017-11-10 21:17:21,476 - octoprint.util.connectivity_checker - INFO - Connectivity changed from offline to online
2017-11-10 21:17:21,959 - octoprint.plugins.softwareupdate - INFO - Loaded version cache from disk
2017-11-10 21:17:25,866 - octoprint.util.pip - INFO - Using "/home/pi/oprint/bin/python -c import sys; sys.argv = ['pip'] + sys.argv[1:]; import pip; pip.main()" as command to invoke pip
2017-11-10 21:17:27,631 - octoprint.util.pip - INFO - Version of pip is 1.1
2017-11-10 21:17:27,634 - octoprint.plugin.core - INFO - Initialized 24 plugin implementation(s)
2017-11-10 21:17:27,656 - octoprint.plugin.core - INFO - 25 plugin(s) registered with the system:
|  Action Trigger (0.1) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_actiontrigger
|  Announcement Plugin (bundled) = /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.5-py2.7.egg/octoprint/plugins/announcements
|  Automatic Shutdown (0.1.4) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_automaticshutdown
|  Autoselect Plugin (0.2.0) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_autoselect
|  BLTouch Plugin (0.2.0) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_BLTouch
|  Core Wizard (bundled) = /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.5-py2.7.egg/octoprint/plugins/corewizard
|  CuraEngine (<= 15.04) (bundled) = /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.5-py2.7.egg/octoprint/plugins/cura
|  Custom Control Editor (0.2.1) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_customControl
|  Discovery (bundled) = /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.5-py2.7.egg/octoprint/plugins/discovery
|  DisplayProgress (0.1.2) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_displayprogress
|  EEPROM Marlin Editor Plugin (1.0.4) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_eeprom_marlin
|  FileManager (0.1.2) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_filemanager
|  FineTuneRptr (0.774) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_finetunerptr
|  GcodeEditor (0.1.1) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_GcodeEditor
|  OctoPrint Anywhere (0.5.2) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_anywhere
|  Plugin Manager (bundled) = /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.5-py2.7.egg/octoprint/plugins/pluginmanager
|  Print History Plugin (1.2) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_printhistory
|  Printer Stats (1.0.0) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_stats
|  Slic3r (1.1.0) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_slic3r
|  Software Update (bundled) = /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.5-py2.7.egg/octoprint/plugins/softwareupdate
|  STL Viewer (0.3.1) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_stlviewer
|  Tempsgraph Plugin (0.2.2) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_tempsgraph
|  TouchUI (0.3.10) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_touchui
| !Virtual Printer (bundled) = /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.5-py2.7.egg/octoprint/plugins/virtual_printer
|  Yamlpatcher (0.1.1) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_yamlpatcher
2017-11-10 21:17:27,732 - octoprint.server - INFO - Reset webasset folder /home/pi/.octoprint/generated/webassets...
2017-11-10 21:17:27,767 - octoprint.server - INFO - Reset webasset folder /home/pi/.octoprint/generated/.webassets-cache...
2017-11-10 21:17:27,899 - octoprint.server.util.flask.collect_plugin_assets - WARNING - Plugin GcodeEditor is referring to non existing css asset css/GcodeEditor.css
2017-11-10 21:17:28,862 - octoprint.server - INFO - Shutting down intermediary server...
2017-11-10 21:17:28,886 - octoprint.server - INFO - Intermediary server shut down
2017-11-10 21:17:28,911 - octoprint.events - INFO - Processing startup event, this is our first event
2017-11-10 21:17:28,960 - octoprint.events - INFO - Adding 1 events to queue that were held back before startup event
2017-11-10 21:17:29,030 - octoprint.filemanager - INFO - Adding backlog items from all storage types to analysis queue...
2017-11-10 21:17:29,120 - octoprint.filemanager - INFO - Added 0 items from storage type "local" to analysis queue
2017-11-10 21:17:29,145 - octoprint.plugins.pluginmanager - INFO - Loaded plugin repository data from disk, was still valid
2017-11-10 21:17:29,326 - octoprint.plugins.pluginmanager - INFO - Loaded notice data from disk, was still valid
2017-11-10 21:17:29,611 - py.warnings - WARNING - /home/pi/oprint/local/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

2017-11-10 21:17:29,613 - py.warnings - WARNING - /home/pi/oprint/local/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

2017-11-10 21:17:29,728 - py.warnings - WARNING - /home/pi/oprint/local/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

2017-11-10 21:17:29,795 - py.warnings - WARNING - /home/pi/oprint/local/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

2017-11-10 21:17:29,832 - py.warnings - WARNING - /home/pi/oprint/local/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

2017-11-10 21:17:30,108 - octoprint.plugins.discovery - INFO - Registered OctoPrint instance "Prusa" for _http._tcp
2017-11-10 21:17:30,119 - octoprint.util.comm - INFO - M110 detected, setting current line number to 0
2017-11-10 21:17:30,132 - octoprint.plugins.discovery - INFO - Registered OctoPrint instance "Prusa" for _octoprint._tcp
2017-11-10 21:17:30,137 - octoprint.plugins.discovery - INFO - Registered OctoPrint instance "Prusa" for SSDP
